CREATE TABLE IF NOT EXISTS projects (
  project_code VARCHAR(100) NOT NULL,
  project_name VARCHAR(255) NOT NULL,
  project_lead_name VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL,
  budget DECIMAL(12,2) NOT NULL,
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (project_code)
);

CREATE TABLE IF NOT EXISTS project_comments (
  project_code VARCHAR(100) NOT NULL,
  comment TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (project_code)
);